"""
Architecture layer for 2repo — topic/component-level docs + Mermaid diagrams.

This is the tier *above* the per-file living wiki (repo/wiki.py): instead of one
page per source file, it produces narrative "how X works" component pages and
architecture diagrams, answering questions the file-by-file wiki cannot ("what
are the main subsystems and how do they interact?").

It is generated by CodeBoarding (https://github.com/CodeBoarding/CodeBoarding,
MIT) — static analysis + LLM reasoning → Mermaid diagrams + component Markdown.

────────────────────────────────────────────────────────────────────────────
THE SWAP SEAM (deprecation insurance)
────────────────────────────────────────────────────────────────────────────
Everything CodeBoarding-specific lives in exactly two private helpers:
    _run_codeboarding()   — how the tool is invoked (CLI, flags, env)
    _codeboarding_dir()   — where the tool writes its native output/baseline
To replace CodeBoarding with another generator later, reimplement those two so
they still drop human/AI-readable Markdown into `<repo>/.codeboarding/`; the rest
of this module (mirroring into <OUT_DIR>/arch/, pruning, the CLI wiring in
repo.py, and index/context folding) is tool-agnostic and stays put.

────────────────────────────────────────────────────────────────────────────
DESIGN (mirrors the wiki layer)
────────────────────────────────────────────────────────────────────────────
- Opt-in and expensive: run via `2repo arch <repo>`, never by `2repo graph`.
- Canonical pages land in `<OUT_DIR>/arch/`, so repo/index.py auto-folds them
  into the semantic index and they surface via `2repo query` + REPO_CONTEXT.md.
- CodeBoarding keeps its own working/baseline dir at `<repo>/.codeboarding/`
  (analysis.json + fingerprint.json), which is what makes its incremental mode
  cheap — analogous to the wiki's .wiki-cache.json. That dir is marked generated
  in shared/config.py so staleness checks and the wiki ignore it.
- The staleness baseline is intentionally NOT rewritten here (only graphify moves
  it), same rule as the wiki.
"""

from __future__ import annotations

import os
import re
import shutil
import subprocess
from pathlib import Path

from repo.vault import mirror_markdown_tree, repo_display_name
from shared import config

_ARCH_SUBPATH = Path(config.OUT_DIR) / "arch"
_CODEBOARDING_SUBPATH = Path(".codeboarding")
# CodeBoarding's incremental baseline.
_BASELINE_FILENAME = "analysis.json"
# CodeBoarding only writes this sidecar when a full analysis completes
# successfully (see repo_utils/fingerprint_diff.py in the vendored package).
# analysis.json alone is NOT proof of a usable baseline — CodeBoarding
# overwrites it at intermediate checkpoints during the abstraction pipeline,
# so a run killed mid-way (Ctrl-C, OOM, timeout) leaves a partial analysis.json
# behind with no fingerprint. Treating that as a valid baseline makes 2repo
# pick "incremental" mode, which CodeBoarding itself then can't actually do
# (it logs `requiresFullAnalysis: true`) — but instead of failing, it silently
# renders a degraded/garbage result from the stale snapshot and exits 0.
# Requiring both files closes that hole: no fingerprint means no baseline, so
# a killed run correctly falls back to a full re-analysis instead of
# corrupting the output.
_FINGERPRINT_FILENAME = "fingerprint.json"

# Provider-credential environment variables CodeBoarding may read. We strip ALL of
# them from the child environment and then set only the selected provider's — the
# 2repo container often has several keys present at once (e.g. OPENAI_API_KEY for
# the `deep` preset alongside a local Ollama), and CodeBoarding selects its
# provider by which credential is set. Exposing exactly one keeps selection
# deterministic regardless of what else is in the container env.
#
# The set mirrors every provider-selection / credential var CodeBoarding recognises
# (see agents/llm_config.py::LLM_PROVIDERS): CodeBoarding picks its provider purely
# by which selection var is present, so scrubbing all of them guarantees exactly one
# survives regardless of what else the container exports.
_PROVIDER_ENV_KEYS = (
    "OPENAI_API_KEY",
    "OPENAI_BASE_URL",
    "ANTHROPIC_API_KEY",
    "GOOGLE_API_KEY",
    "OLLAMA_BASE_URL",
    "OLLAMA_HOST",
    "OLLAMA_API_KEY",
    "VERCEL_API_KEY",
    "VERCEL_BASE_URL",
    "AWS_BEARER_TOKEN_BEDROCK",
    "CEREBRAS_API_KEY",
    "DEEPSEEK_API_KEY",
    "DEEPSEEK_BASE_URL",
    "GLM_API_KEY",
    "GLM_BASE_URL",
    "KIMI_API_KEY",
    "KIMI_BASE_URL",
    "OPENROUTER_API_KEY",
    "ORCAROUTER_API_KEY",
    "LITELLM_BASE_URL",
    "LITELLM_API_KEY",
    "AGENT_MODEL",
    "PARSING_MODEL",
)

# Inline renderer: CodeBoarding 0.13.8's `--local` analysis writes only analysis.json
# (the remote path renders Markdown, the local path does not), and the version ships
# no `codeboarding-render` console script. So we drive render_docs() ourselves, in
# CodeBoarding's own venv interpreter (its workflow packages aren't importable from
# the scripts interpreter). This is the one render-shaped detail that would change if
# CodeBoarding is ever swapped out — kept beside _run_codeboarding on purpose.
_RENDER_SCRIPT = """\
import sys
from pathlib import Path
from codeboarding_workflows.rendering import render_docs

analysis_path, out_dir, repo_name = sys.argv[1], sys.argv[2], sys.argv[3]
render_docs(
    analysis_path=Path(analysis_path),
    repo_name=repo_name,
    repo_ref="",
    temp_dir=Path(out_dir),
    format=".md",
    root_name="overview",
    demo_mode=False,
)
"""


def arch_dir(repo_path: str) -> Path:
    """Return the canonical (indexed) architecture output directory."""
    return Path(repo_path) / _ARCH_SUBPATH


def _codeboarding_dir(repo_path: str) -> Path:
    """Return CodeBoarding's native working/baseline directory."""
    return Path(repo_path) / _CODEBOARDING_SUBPATH


def _has_baseline(repo_path: str) -> bool:
    cb_dir = _codeboarding_dir(repo_path)
    return (cb_dir / _BASELINE_FILENAME).is_file() and (cb_dir / _FINGERPRINT_FILENAME).is_file()


def _provider_env(provider: str, model: str) -> dict[str, str]:
    """Build a child-process env exposing only the selected provider's credentials.

    Raises ValueError for providers CodeBoarding cannot use (with actionable text).
    """
    env = {k: v for k, v in os.environ.items() if k not in _PROVIDER_ENV_KEYS}

    # Privacy: CodeBoarding telemetry is on by default. 2repo is local-first, so
    # disable it unconditionally (belt-and-suspenders with the Dockerfile env).
    env["CODEBOARDING_TELEMETRY"] = "false"
    env["DO_NOT_TRACK"] = "1"

    if provider == "ollama":
        # config.OLLAMA_URL is already stripped of the trailing /v1 that graphify
        # needs; CodeBoarding wants the bare base URL (e.g. http://ollama:11434).
        env["OLLAMA_BASE_URL"] = config.OLLAMA_URL
    elif provider == "openai":
        key = os.getenv("OPENAI_API_KEY")
        if not key:
            raise ValueError(
                "OPENAI_API_KEY not set — required for an openai preset with '2repo arch'. "
                "Add it to .env, or use a local preset: 2repo arch <repo> --preset fast"
            )
        env["OPENAI_API_KEY"] = key
        base_url = os.getenv("OPENAI_BASE_URL")
        if base_url:
            env["OPENAI_BASE_URL"] = base_url
    elif provider == "anthropic":
        key = os.getenv("ANTHROPIC_API_KEY")
        if not key:
            raise ValueError(
                "ANTHROPIC_API_KEY not set — required for an anthropic preset with '2repo arch'. "
                "Add it to .env, or use a local preset: 2repo arch <repo> --preset fast"
            )
        env["ANTHROPIC_API_KEY"] = key
    elif provider == "claude-code":
        # graphify/wiki can route through the `claude` CLI subscription, but
        # CodeBoarding has no claude-cli backend — it needs a real API credential.
        raise ValueError(
            "provider 'claude-code' is not supported by '2repo arch' — CodeBoarding has no "
            "CLI/subscription backend. Use a preset that points at ollama, openai, or anthropic, "
            "e.g. 2repo arch <repo> --preset fast (or set REPO_PRESET_ARCH)."
        )
    else:
        raise ValueError(
            f"provider '{provider}' has no CodeBoarding mapping — supported: ollama, openai, anthropic"
        )

    # CodeBoarding uses one model for the agent and one for parsing; point both at
    # the resolved preset model so the whole run uses a single, predictable model.
    env["AGENT_MODEL"] = model
    env["PARSING_MODEL"] = model

    # CodeBoarding hardcodes its agent-invocation timeout (300s first attempt,
    # 600s on retry) with no native override — see Dockerfile.scripts for the
    # build-time patch that makes it read these two env vars instead. A slow
    # local model needs more headroom than that; since retries restart the same
    # reasoning chain from scratch, one generous attempt beats five short ones.
    agent_timeout = os.getenv("REPO_ARCH_AGENT_TIMEOUT")
    if agent_timeout:
        env["CODEBOARDING_AGENT_TIMEOUT_FIRST"] = agent_timeout
        env["CODEBOARDING_AGENT_TIMEOUT_RETRY"] = agent_timeout

    # Context-window budget (see patches/codeboarding/context_budget.py). CodeBoarding
    # asks Ollama for the model's context length and gets the *architectural* max
    # (262k for a Qwen-class model), not the window the server actually runs
    # (OLLAMA_NUM_CTX) — and it never budgets against either. Its tool loop keeps
    # appending file reads until the prompt overflows; Ollama then silently drops
    # the oldest tokens (the task itself) and the turn fails, which CodeBoarding
    # retries from scratch up to 5×. Tell it the real window so the patched agent
    # stops reading before the overflow and reads in chunks sized for it.
    window = _context_window(provider)
    if window:
        env["CODEBOARDING_CONTEXT_WINDOW"] = str(window)
        env["CODEBOARDING_READ_FILE_LINES"] = str(_read_chunk_lines(window))

    return env


def _context_window(provider: str) -> int | None:
    """Usable context window for the arch run, in tokens.

    REPO_ARCH_CONTEXT_TOKENS wins when set (any provider; 0 disables the budget).
    Otherwise Ollama presets use OLLAMA_NUM_CTX — the only party that knows the
    server-side window is our own .env. Cloud providers get None: their windows
    are large and CodeBoarding's own catalogs describe them correctly.
    """
    raw = os.getenv("REPO_ARCH_CONTEXT_TOKENS", "").strip()
    if raw:
        if not raw.isdigit():
            raise ValueError(f"REPO_ARCH_CONTEXT_TOKENS must be a whole number of tokens, got {raw!r}")
        return int(raw) or None
    if provider == "ollama":
        return config.OLLAMA_NUM_CTX
    return None


# CodeBoarding's readFile returns 300 lines per call. At ~270 tokens per 100
# numbered lines of code, that is ~1/10 of a 32k window per read — a handful of
# reads fill the conversation before the agent has reasoned about anything.
# Scale the chunk with the window (120 lines at 32k, 240 at 64k, stock 300
# from ~80k up) so a small window buys more, smaller reads instead of fewer,
# mostly-unused big ones. Never below 60: a chunk smaller than a typical
# function is useless for the "look at this implementation" reads the tool is for.
_READ_CHUNK_MAX_LINES = 300
_READ_CHUNK_MIN_LINES = 60
_READ_CHUNK_TOKENS_PER_LINE = 270


def _read_chunk_lines(window: int) -> int:
    return max(_READ_CHUNK_MIN_LINES, min(_READ_CHUNK_MAX_LINES, window // _READ_CHUNK_TOKENS_PER_LINE))


def _codeboarding_python() -> str:
    """Locate the interpreter of CodeBoarding's isolated venv.

    render_docs() lives in CodeBoarding's workflow packages, installed in a separate
    venv (see Dockerfile.scripts) that the scripts interpreter can't import from.
    Resolve the venv's python via the `codeboarding` launcher symlink so we stay
    agnostic of the exact install path; overridable with CODEBOARDING_PYTHON.
    """
    override = os.getenv("CODEBOARDING_PYTHON")
    if override:
        return override
    launcher = shutil.which("codeboarding")
    if launcher:
        candidate = Path(launcher).resolve().parent / "python"
        if candidate.exists():
            return str(candidate)
    return "python"


def _render_markdown(repo_path: str, env: dict[str, str]) -> None:
    """Render .codeboarding/analysis.json into Markdown pages in the same directory.

    Needed because CodeBoarding's local analysis emits only analysis.json; the
    rendered overview.md + per-component pages are what _mirror_pages picks up.
    """
    cb_dir = _codeboarding_dir(repo_path)
    analysis = cb_dir / _BASELINE_FILENAME
    if not analysis.is_file():
        raise RuntimeError(
            f"codeboarding produced no {analysis} — cannot render Markdown "
            "(check the provider credential/model and language-server setup)"
        )
    cmd = [
        _codeboarding_python(), "-c", _RENDER_SCRIPT,
        str(analysis), str(cb_dir), Path(repo_path).name,
    ]
    proc = subprocess.run(cmd, cwd=repo_path, env=env)
    if proc.returncode != 0:
        raise RuntimeError(
            f"codeboarding Markdown rendering failed with code {proc.returncode} — "
            "see output above"
        )


def _run_codeboarding(repo_path: str, *, provider: str, model: str, incremental: bool) -> None:
    """Invoke the CodeBoarding CLI (the only place that knows the tool's interface).

    Writes native output to <repo>/.codeboarding/ (analysis.json baseline), then
    renders it to Markdown in the same directory. Raises RuntimeError on failure.
    """
    env = _provider_env(provider, model)
    mode = "incremental" if incremental else "full"
    # --local <path>: analyze the working tree in place (no clone). This version
    # writes analysis.json only; Markdown is rendered by _render_markdown below.
    cmd = ["codeboarding", mode, "--local", repo_path]
    print(f"Arch     : codeboarding {mode}  provider={provider}  model={model}")
    proc = subprocess.run(cmd, cwd=repo_path, env=env)
    if proc.returncode != 0:
        raise RuntimeError(
            f"codeboarding {mode} exited with code {proc.returncode} — "
            "see output above (check the provider credential/model and language-server setup)"
        )
    _render_markdown(repo_path, env)


def _rendered_pages(repo_path: str) -> list[Path]:
    """Return the Markdown pages CodeBoarding rendered into .codeboarding/."""
    cb_dir = _codeboarding_dir(repo_path)
    if not cb_dir.is_dir():
        return []
    return sorted(p for p in cb_dir.glob("*.md") if p.is_file())


# CodeBoarding bakes a promotional badge line (shields.io / app.codeboarding.org /
# mailto) and a trailing FAQ link into every rendered page, regardless of demo_mode.
_PROMO_BADGE_PREFIX = "[![CodeBoarding]"
_PROMO_FAQ_PREFIX = "### [FAQ]"


def _clean_page(text: str) -> str:
    """Strip CodeBoarding's promo badge line and trailing FAQ link.

    These are external marketing/tracking links, not documentation. 2repo is
    local-first and these pages are folded into the semantic index, so we drop the
    promo noise while leaving the architecture prose and Mermaid diagrams intact.
    Conservative: only removes the two known promo constructs; anything else it
    doesn't recognise passes through unchanged.
    """
    kept = [
        line for line in text.splitlines()
        if not line.startswith(_PROMO_BADGE_PREFIX)
        and not line.startswith(_PROMO_FAQ_PREFIX)
    ]
    cleaned = re.sub(r"\n{3,}", "\n\n", "\n".join(kept))
    return cleaned.rstrip() + "\n"


def _page_frontmatter(repo_path: str, name: str) -> str:
    """YAML frontmatter tagging an architecture page for the vault.

    Mirrors the module tier's scheme so a single Obsidian graph filter
    (`-tag:2repo`) hides everything 2repo generates, leaving hand-written notes.
    """
    return "\n".join(
        [
            "---",
            "tags:",
            "  - 2repo",
            "  - 2repo/arch",
            f"  - project/{repo_display_name(repo_path)}",
            "type: architecture",
            f"component: {name.removesuffix('.md')}",
            "---",
            "",
            "",
        ]
    )


def _mirror_pages(repo_path: str) -> tuple[list[str], list[str]]:
    """Copy rendered pages into <OUT_DIR>/arch/ and prune ones no longer present.

    Returns (written, removed) page filenames. Mirroring (rather than pointing the
    index at .codeboarding/ directly) keeps every indexed artifact under
    OUT_DIR and keeps the swap seam clean: any future generator only has to
    produce Markdown in .codeboarding/.
    """
    out_dir = arch_dir(repo_path)
    out_dir.mkdir(parents=True, exist_ok=True)

    rendered = _rendered_pages(repo_path)
    source_names = {p.name for p in rendered}

    written: list[str] = []
    for page in rendered:
        cleaned = _clean_page(page.read_text(encoding="utf-8"))
        (out_dir / page.name).write_text(
            _page_frontmatter(repo_path, page.name) + cleaned, encoding="utf-8"
        )
        written.append(page.name)

    removed: list[str] = []
    for existing in out_dir.glob("*.md"):
        if existing.name not in source_names:
            existing.unlink()
            removed.append(existing.name)
    return written, removed


def generate(
    repo_path: str,
    *,
    provider: str,
    model: str,
    force_all: bool = False,
    dry_run: bool = False,
) -> dict[str, object]:
    """Generate/update the architecture layer and return a summary.

    Uses CodeBoarding's incremental mode when a baseline exists (cheap), falling
    back to a full analysis otherwise or when force_all is set.
    """
    incremental = _has_baseline(repo_path) and not force_all
    mode = "incremental" if incremental else "full"

    if dry_run:
        reason = (
            "baseline present" if incremental
            else ("--force-all" if force_all else "no baseline yet")
        )
        print(f"Arch     : would run codeboarding {mode} ({reason}) — no LLM calls made")
        return {"artifact": str(_ARCH_SUBPATH), "dry_run": True, "mode": mode}

    _run_codeboarding(repo_path, provider=provider, model=model, incremental=incremental)

    written, removed = _mirror_pages(repo_path)
    if not written:
        raise RuntimeError(
            f"codeboarding produced no Markdown pages in {_codeboarding_dir(repo_path)} — "
            f"nothing to mirror into {_ARCH_SUBPATH}/"
        )
    for name in written:
        print(f"Arch     : wrote {_ARCH_SUBPATH}/{name}")
    for name in removed:
        print(f"Arch     : pruned {_ARCH_SUBPATH}/{name}")

    return {
        "artifact": str(_ARCH_SUBPATH),
        "dry_run": False,
        "mode": mode,
        "written": written,
        "removed": removed,
        "page_count": len(written),
    }


def mirror_to_vault(repo_path: str, vault_path: Path) -> Path:
    """Mirror <OUT_DIR>/arch into the Obsidian vault under Projects/<repo>/Generated/Architecture/."""
    source = arch_dir(repo_path)
    if not source.exists() or not any(source.glob("*.md")):
        raise FileNotFoundError(f"architecture layer not generated yet: {source}")
    project_root = vault_path / "Projects" / repo_display_name(repo_path)
    return mirror_markdown_tree(source, project_root / "Generated" / "Architecture")
