"""
Inject 2repo context into editor-specific instruction files.

This module writes/updates small "bridge" files (Claude, Copilot, Cursor) that
point to <OUT_DIR>/REPO_CONTEXT.md so assistants can ground responses in the
latest generated repository artifacts.

It also writes the two repo-hygiene files that make the generated tree behave:
.graphifyignore (so graphify never re-ingests our own Markdown as source) and
.gitattributes (so the committed artifacts read as generated in diffs).
"""

from __future__ import annotations

import re
from collections.abc import Callable
from pathlib import Path

from shared import config

_MARKER_START = "<!-- 2repo:start — regenerate with: 2repo <repo-path> -->"
_MARKER_END = "<!-- 2repo:end -->"
_MARKER_PATTERN = re.compile(re.escape(_MARKER_START) + r".*?" + re.escape(_MARKER_END), re.DOTALL)

# .graphifyignore and .gitattributes are line-oriented and treat <!-- --> as
# content, so the managed block there is delimited by # comments instead.
_HASH_MARKER_START = "# 2repo:start — regenerate with: 2repo <repo-path>"
_HASH_MARKER_END = "# 2repo:end"
_HASH_MARKER_PATTERN = re.compile(
    re.escape(_HASH_MARKER_START) + r".*?" + re.escape(_HASH_MARKER_END), re.DOTALL
)

_OUT = config.OUT_DIR
_PRIMARY_CONTEXT_PATH = f"{_OUT}/REPO_CONTEXT.md"
# (path, human description) pairs — the single source for both the reference
# path list and the described artifact list, so they can never drift apart.
# GRAPH_REPORT.md is graphify's own product and therefore lives one level deeper.
_CONTEXT_ARTIFACTS = (
    (f"{config.GRAPHIFY_OUT}/GRAPH_REPORT.md", "structural and semantic code graph report"),
    (f"{_OUT}/EXECUTION.md", "runnable build/test/CI/migration knowledge"),
    (f"{_OUT}/REPO_MEMORY.md", "durable repository memory entries"),
    (f"{_OUT}/repo-index.json", "semantic retrieval index"),
)
_CONTEXT_REFERENCE_PATHS = tuple(path for path, _ in _CONTEXT_ARTIFACTS)

# Public: the canonical set of AI integration targets. repo.py imports this so
# the CLI choices and this module's validation share one definition.
AI_TARGETS = ("claude", "copilot", "cursor", "neutral")


def _expanded_sources_inline() -> str:
    return ", ".join(f"`{path}`" for path in _CONTEXT_REFERENCE_PATHS)


def _claude_inline() -> str:
    """Managed CLAUDE.md block: an @-import plus what to do with it.

    Claude Code auto-loads CLAUDE.md and resolves @-imports, so the import is
    what actually puts REPO_CONTEXT.md in context. REPO_CONTEXT.md then only
    *names* the other artifacts — they are backticked paths, not imports — so
    without the instruction below Claude sees a list of filenames and no reason
    to open any of them. Copilot and Cursor get the same directive.
    """
    return (
        f"{_MARKER_START}\n"
        "Use the repository context generated by 2repo before proposing changes.\n"
        f"@{_PRIMARY_CONTEXT_PATH}\n"
        f"It lists the expanded sources: {_expanded_sources_inline()}. Read the ones\n"
        "relevant to the task, or retrieve across all of them with\n"
        '`2repo query <repo-path> "your question"`.\n'
        f"{_MARKER_END}"
    )


def _copilot_inline() -> str:
    return (
        f"{_MARKER_START}\n"
        "Use the repository context generated by 2repo before proposing changes.\n"
        f"Primary context: `{_PRIMARY_CONTEXT_PATH}`\n"
        f"Expanded sources: {_expanded_sources_inline()}\n"
        f"{_MARKER_END}"
    )


def _cursor_rule() -> str:
    lines = [
        "---",
        "description: 2repo repository context",
        'globs: ["**/*"]',
        "alwaysApply: true",
        "---",
        "",
        "# Intentional: repository context must be applied globally for consistent sessions.",
        f"Use `{_PRIMARY_CONTEXT_PATH}` as the primary repository context.",
        "For detailed references consult:",
    ]
    lines.extend(f"- `{path}`" for path in _CONTEXT_REFERENCE_PATHS)
    lines.append("")
    return "\n".join(lines)


def _write_if_changed(path: Path, *, content: str) -> bool:
    if path.exists():
        if path.read_text(encoding="utf-8") == content:
            return False
        path.write_text(content, encoding="utf-8")
        return True
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return True


def _replace_or_append(
    path: Path,
    *,
    block: str,
    marker_start: str = _MARKER_START,
    pattern: re.Pattern[str] = _MARKER_PATTERN,
) -> bool:
    """Replace the managed marker block in a file, or append/create it if missing."""
    if path.exists():
        content = path.read_text(encoding="utf-8")
        if marker_start in content:
            updated = pattern.sub(block, content)
            return _write_if_changed(path, content=updated)
        updated = content.rstrip() + "\n\n" + block + "\n"
        return _write_if_changed(path, content=updated)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(block + "\n", encoding="utf-8")
    return True


def _graphifyignore_block() -> str:
    """Managed .graphifyignore block keeping generated docs out of the graph.

    graphify prunes exactly one directory on its own: the one it writes to,
    matched by basename(GRAPHIFY_OUT). Everything generated outside it —
    2repo's wiki/, arch/ and EXECUTION.md, CodeBoarding's working dir — is
    ordinary Markdown as far as graphify is concerned, and would be extracted
    back into the graph on the next run, feeding generated prose into the next
    generation of generated prose.
    """
    lines = [
        _HASH_MARKER_START,
        "# Generated documentation must never be re-ingested as source.",
        *(f"{name}/" for name in config.GRAPHIFY_IGNORE_DIRS),
        _HASH_MARKER_END,
    ]
    return "\n".join(lines)


def _gitattributes_block() -> str:
    """Managed .gitattributes block marking the generated tree as generated.

    The artifacts are meant to be committed (regenerating them costs real LLM
    tokens, and the incremental caches that keep re-runs cheap live in the same
    tree), so they show up in every diff. linguist-generated collapses them in
    GitHub reviews. Deliberately NOT '-diff': that suppresses the textual diff
    everywhere, including local `git diff` when you actually want to look.
    """
    return "\n".join([
        _HASH_MARKER_START,
        f"{_OUT}/** linguist-generated=true",
        _HASH_MARKER_END,
    ])


def _gitignore_block() -> str:
    """Managed .gitignore block excluding regeneration-only caches and duplicates.

    Deliberately narrow: wiki/, arch/, modules/, EXECUTION.md, REPO_MEMORY.md,
    REPO_CONTEXT.md and repo-index.json are committed on purpose (regenerating
    them costs real LLM time/tokens, or needs 2repo/graphify installed — a
    teammate without that tooling or a capable machine should still be able to
    read and query them). Everything listed here only speeds up a *future*
    regeneration and has zero value to a reader:
      - graphify's raw graph.json/manifest.json/.graphify_* dumps — structural
        data, not prose (see index.py's _artifact_files for why these are also
        excluded from the semantic index, not just git)
      - graphify's own incremental AST/semantic cache
      - graphify's dated snapshot directories, which duplicate its live output
      - the wiki/module incremental content-hash caches
      - CodeBoarding's native working dir (.codeboarding/): its committed,
        canonical copy already lives in <OUT_DIR>/arch/
    """
    graphify_out = config.GRAPHIFY_OUT
    return "\n".join([
        _HASH_MARKER_START,
        f"{graphify_out}/cache/",
        f"{graphify_out}/graph.json",
        f"{graphify_out}/manifest.json",
        f"{graphify_out}/.graphify_analysis.json",
        f"{graphify_out}/.graphify_labels.json*",
        f"{graphify_out}/[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]/",
        f"{_OUT}/wiki/.wiki-cache.json",
        f"{_OUT}/modules/.modules-cache.json",
        ".codeboarding/",
        _HASH_MARKER_END,
    ])


def _write_repo_hygiene(repo: Path) -> list[str]:
    """Write the ignore/attribute files the generated tree needs, in any AI target."""
    outputs: list[str] = []
    for filename, block in (
        (".graphifyignore", _graphifyignore_block()),
        (".gitattributes", _gitattributes_block()),
        (".gitignore", _gitignore_block()),
    ):
        path = repo / filename
        if _replace_or_append(
            path,
            block=block,
            marker_start=_HASH_MARKER_START,
            pattern=_HASH_MARKER_PATTERN,
        ):
            outputs.append(str(path))
    return outputs


def _inject_claude(repo: Path) -> list[str]:
    claude_md = repo / "CLAUDE.md"
    return [str(claude_md)] if _replace_or_append(claude_md, block=_claude_inline()) else []


def _inject_copilot(repo: Path) -> list[str]:
    copilot = repo / ".github" / "copilot-instructions.md"
    return [str(copilot)] if _replace_or_append(copilot, block=_copilot_inline()) else []


def _inject_cursor(repo: Path) -> list[str]:
    cursor_rule = repo / ".cursor" / "rules" / "2repo.mdc"
    return [str(cursor_rule)] if _write_if_changed(cursor_rule, content=_cursor_rule()) else []


def _inject_neutral(_repo: Path) -> list[str]:
    return []


_TARGET_WRITERS: dict[str, Callable[[Path], list[str]]] = {
    "claude": _inject_claude,
    "copilot": _inject_copilot,
    "cursor": _inject_cursor,
    "neutral": _inject_neutral,
}


def inject_for_target(repo_path: str, *, ai_target: str) -> list[str]:
    """Write integration files for one AI target and return created/updated paths."""
    repo = Path(repo_path)
    context = repo / _OUT / "REPO_CONTEXT.md"
    if not context.exists():
        raise FileNotFoundError(f"required context artifact missing: {context}")
    if ai_target not in AI_TARGETS:
        raise ValueError(f"invalid ai target '{ai_target}' (expected one of: {', '.join(AI_TARGETS)})")

    # Hygiene files are about the generated tree itself, not the assistant, so
    # they are written even for the neutral target.
    return _write_repo_hygiene(repo) + _TARGET_WRITERS[ai_target](repo)


def write_repo_context(
    repo_path: str,
    *,
    provider: str,
    model: str,
    index_revision: str,
    index_chunks: int,
    memory_count: int,
) -> Path:
    """Build <OUT_DIR>/REPO_CONTEXT.md summarizing canonical 2repo artifacts."""
    repo = Path(repo_path)
    out = repo / _OUT / "REPO_CONTEXT.md"
    out.parent.mkdir(parents=True, exist_ok=True)

    lines: list[str] = []
    lines.append("# Repo Context")
    lines.append("")
    lines.append("_Canonical 2repo context source for AI editors._")
    lines.append("")
    lines.append("## Core Artifacts")
    for artifact_path, description in _CONTEXT_ARTIFACTS:
        lines.append(f"- `{artifact_path}` — {description}")
    wiki_dir = repo / _OUT / "wiki"
    if wiki_dir.is_dir() and any(wiki_dir.glob("*.md")):
        lines.append(
            f"- `{_OUT}/wiki/` — living wiki: per-file documentation pages "
            "plus `OVERVIEW.md` (generated — do not edit by hand; regenerate with `2repo wiki <repo-path>`)"
        )
    arch_dir = repo / _OUT / "arch"
    if arch_dir.is_dir() and any(arch_dir.glob("*.md")):
        lines.append(
            f"- `{_OUT}/arch/` — architecture layer: component/topic pages with "
            "Mermaid diagrams plus `overview.md` (generated — do not edit by hand; "
            "regenerate with `2repo arch <repo-path>`)"
        )
    lines.append("")
    lines.append("## Index Metadata")
    lines.append(f"- Provider: `{provider}`")
    lines.append(f"- Model: `{model}`")
    lines.append(f"- Index revision: `{index_revision}`")
    lines.append(f"- Indexed chunks: `{index_chunks}`")
    lines.append(f"- Memory entries: `{memory_count}`")
    lines.append("")
    lines.append("## Query")
    lines.append("- Semantic query: `2repo query <repo-path> \"your question\" --top-k 5`")
    lines.append("- Add durable memory: `2repo remember <repo-path> \"fact/decision/runbook\" --kind fact`")
    lines.append("")

    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return out
