#!/usr/bin/env bash
# ollama.sh — manage the containerized Ollama from the host.
#
#   scripts/ollama.sh install   # put an `ollama` command on the host that talks to the container
#   scripts/ollama.sh update    # pull the newest ollama image and recreate the container
#   scripts/ollama.sh fix-gpu   # regenerate the NVIDIA CDI spec (fixes "Could not locate device X:Y")
#   scripts/ollama.sh status    # versions, GPU, models
#
# Models live in ~/.ollama on the host, so nothing here ever deletes a model.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
[ -f "$ROOT/.env" ] && set -a && . "$ROOT/.env" && set +a
ENGINE="${CONTAINER_ENGINE:-docker}"
SERVICE="ollama"
SHIM="$HOME/.local/bin/ollama"

compose() { (cd "$ROOT" && "$ENGINE" compose "$@" 2>&1 | grep -v '^>>>>' || true); }
container_name() { "$ENGINE" ps --format '{{.Names}}' | grep -m1 "_${SERVICE}_1\$\|-${SERVICE}-1\$" || true; }

cmd_install() {
    if command -v ollama >/dev/null && [ "$(command -v ollama)" != "$SHIM" ]; then
        echo "A host Ollama is installed at $(command -v ollama)." >&2
        echo "Remove it first (it conflicts on port 11434 and GPU):" >&2
        echo "  sudo systemctl disable --now ollama; sudo rm -rf /etc/systemd/system/ollama.service /usr/local/bin/ollama /usr/local/lib/ollama; sudo userdel ollama" >&2
        exit 1
    fi
    mkdir -p "$(dirname "$SHIM")"
    cat > "$SHIM" <<SHIMEOF
#!/usr/bin/env bash
# Host-side \`ollama\` shim → forwards to the knowledge-hub container.
# Generated by $ROOT/scripts/ollama.sh install
set -euo pipefail
ROOT="$ROOT"
ENGINE="$ENGINE"
name() { "\$ENGINE" ps --format '{{.Names}}' | grep -m1 '_ollama_1\$\|-ollama-1\$' || true; }
C="\$(name)"
if [ -z "\$C" ]; then
    echo "ollama container not running — starting it..." >&2
    (cd "\$ROOT" && "\$ENGINE" compose up -d ollama 2>&1 | grep -v '^>>>>' >&2 || true)
    for _ in \$(seq 1 30); do C="\$(name)"; [ -n "\$C" ] && "\$ENGINE" exec "\$C" ollama --version >/dev/null 2>&1 && break; sleep 1; done
fi
T=(-i); [ -t 0 ] && [ -t 1 ] && T=(-it)
exec "\$ENGINE" exec "\${T[@]}" "\$C" ollama "\$@"
SHIMEOF
    chmod +x "$SHIM"
    echo "Installed $SHIM"
    case ":$PATH:" in *":$HOME/.local/bin:"*) ;; *) echo "Add to your shell rc:  export PATH=\"\$HOME/.local/bin:\$PATH\"" ;; esac
    hash -r 2>/dev/null || true
    "$SHIM" --version
}

cmd_update() {
    echo "Pulling newest ollama image..."
    "$ENGINE" pull docker.io/ollama/ollama:latest | tail -1
    echo "Recreating container (models in ~/.ollama are untouched)..."
    compose up -d --force-recreate "$SERVICE"
    sleep 3
    "$ENGINE" exec "$(container_name)" ollama --version
    "$ENGINE" image prune -f >/dev/null && echo "Old images pruned."
}

cmd_fix_gpu() {
    command -v nvidia-ctk >/dev/null || { echo "nvidia-ctk not found (install nvidia-container-toolkit)"; exit 1; }
    echo "Regenerating /etc/cdi/nvidia.yaml (needs sudo)..."
    sudo nvidia-ctk cdi generate --output=/etc/cdi/nvidia.yaml >/dev/null
    compose up -d --force-recreate "$SERVICE"
    sleep 3
    "$ENGINE" exec "$(container_name)" nvidia-smi --query-gpu=name --format=csv,noheader
}

cmd_status() {
    C="$(container_name)"
    [ -n "$C" ] || { echo "container not running"; exit 1; }
    echo "container : $C"
    echo "server    : $("$ENGINE" exec "$C" ollama --version)"
    echo "host cmd  : $(command -v ollama || echo 'none — run: scripts/ollama.sh install')"
    echo "gpu       : $("$ENGINE" exec "$C" nvidia-smi --query-gpu=name,memory.used --format=csv,noheader 2>/dev/null || echo 'n/a')"
    echo "models    :"; "$ENGINE" exec "$C" ollama list | tail -n +2 | awk '{print "  " $1 "  " $3 $4}'
}

case "${1:-}" in
    install) cmd_install ;;
    update)  cmd_update ;;
    fix-gpu) cmd_fix_gpu ;;
    status)  cmd_status ;;
    *) sed -n '2,9p' "$0"; exit 1 ;;
esac
