from __future__ import annotations

import re
from pathlib import Path


_MARKER_START = "<!-- 2repo:start — regenerate with: 2repo <repo-path> -->"
_MARKER_END = "<!-- 2repo:end -->"
_MARKER_PATTERN = re.compile(re.escape(_MARKER_START) + r".*?" + re.escape(_MARKER_END), re.DOTALL)


_CLAUDE_INLINE = (
    f"{_MARKER_START}\n"
    "@graphify-out/REPO_CONTEXT.md\n"
    f"{_MARKER_END}"
)

_COPILOT_INLINE = (
    f"{_MARKER_START}\n"
    "Use the repository context generated by 2repo before proposing changes.\n"
    "Primary context: `graphify-out/REPO_CONTEXT.md`\n"
    "Expanded sources: `graphify-out/GRAPH_REPORT.md`, `graphify-out/EXECUTION.md`, `graphify-out/REPO_MEMORY.md`\n"
    f"{_MARKER_END}"
)

_CURSOR_RULE = """---
description: 2repo repository context
globs: ["**/*"]
alwaysApply: true
---

# Intentional: repository context must be applied globally for consistent sessions.
Use `graphify-out/REPO_CONTEXT.md` as the primary repository context.
For detailed references consult:
- `graphify-out/GRAPH_REPORT.md`
- `graphify-out/EXECUTION.md`
- `graphify-out/REPO_MEMORY.md`
"""


def _replace_or_append(path: Path, *, block: str) -> None:
    if path.exists():
        content = path.read_text(encoding="utf-8")
        if _MARKER_START in content:
            updated = _MARKER_PATTERN.sub(block, content)
            path.write_text(updated, encoding="utf-8")
            return
        path.write_text(content.rstrip() + "\n\n" + block + "\n", encoding="utf-8")
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(block + "\n", encoding="utf-8")


def inject_all(repo_path: str) -> list[str]:
    repo = Path(repo_path)
    context = repo / "graphify-out" / "REPO_CONTEXT.md"
    if not context.exists():
        raise FileNotFoundError(f"required context artifact missing: {context}")

    outputs: list[str] = []

    claude_dir = repo / ".claude"
    claude_dir.mkdir(parents=True, exist_ok=True)
    knowledge = claude_dir / "KNOWLEDGE.md"
    knowledge.write_text("@../graphify-out/REPO_CONTEXT.md\n", encoding="utf-8")
    outputs.append(str(knowledge))

    claude_md = repo / "CLAUDE.md"
    _replace_or_append(claude_md, block=_CLAUDE_INLINE)
    outputs.append(str(claude_md))

    copilot = repo / ".github" / "copilot-instructions.md"
    _replace_or_append(copilot, block=_COPILOT_INLINE)
    outputs.append(str(copilot))

    cursor_rule = repo / ".cursor" / "rules" / "2repo.mdc"
    cursor_rule.parent.mkdir(parents=True, exist_ok=True)
    cursor_rule.write_text(_CURSOR_RULE, encoding="utf-8")
    outputs.append(str(cursor_rule))

    return outputs


def write_repo_context(
    repo_path: str,
    *,
    provider: str,
    model: str,
    index_revision: str,
    index_chunks: int,
    memory_count: int,
) -> Path:
    repo = Path(repo_path)
    out = repo / "graphify-out" / "REPO_CONTEXT.md"
    out.parent.mkdir(parents=True, exist_ok=True)

    lines: list[str] = []
    lines.append("# Repo Context")
    lines.append("")
    lines.append("_Canonical 2repo context source for AI editors._")
    lines.append("")
    lines.append("## Core Artifacts")
    lines.append("- `graphify-out/GRAPH_REPORT.md` — structural and semantic code graph report")
    lines.append("- `graphify-out/EXECUTION.md` — runnable build/test/CI/migration knowledge")
    lines.append("- `graphify-out/REPO_MEMORY.md` — durable repository memory entries")
    lines.append("- `graphify-out/repo-index.json` — semantic retrieval index")
    lines.append("")
    lines.append("## Index Metadata")
    lines.append(f"- Provider: `{provider}`")
    lines.append(f"- Model: `{model}`")
    lines.append(f"- Index revision: `{index_revision}`")
    lines.append(f"- Indexed chunks: `{index_chunks}`")
    lines.append(f"- Memory entries: `{memory_count}`")
    lines.append("")
    lines.append("## Query")
    lines.append("- Semantic query: `2repo <repo-path> --query \"your question\" --top-k 5`")
    lines.append("- Add durable memory: `2repo <repo-path> --remember \"fact/decision/runbook\" --memory-kind fact`")
    lines.append("")

    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return out
