from __future__ import annotations

"""
Inject 2repo context into editor-specific instruction files.

This module writes/updates small "bridge" files (Claude, Copilot, Cursor) that
point to graphify-out/REPO_CONTEXT.md so assistants can ground responses in the
latest generated repository artifacts.
"""

import re
from pathlib import Path
from typing import Callable


_MARKER_START = "<!-- 2repo:start — regenerate with: 2repo <repo-path> -->"
_MARKER_END = "<!-- 2repo:end -->"
_MARKER_PATTERN = re.compile(re.escape(_MARKER_START) + r".*?" + re.escape(_MARKER_END), re.DOTALL)

_PRIMARY_CONTEXT_PATH = "graphify-out/REPO_CONTEXT.md"
_CONTEXT_REFERENCE_PATHS = (
    "graphify-out/GRAPH_REPORT.md",
    "graphify-out/EXECUTION.md",
    "graphify-out/REPO_MEMORY.md",
    "graphify-out/repo-index.json",
)
_CONTEXT_ARTIFACTS = (
    ("graphify-out/GRAPH_REPORT.md", "structural and semantic code graph report"),
    ("graphify-out/EXECUTION.md", "runnable build/test/CI/migration knowledge"),
    ("graphify-out/REPO_MEMORY.md", "durable repository memory entries"),
    ("graphify-out/repo-index.json", "semantic retrieval index"),
)

_CLAUDE_INLINE = (
    f"{_MARKER_START}\n"
    f"@{_PRIMARY_CONTEXT_PATH}\n"
    f"{_MARKER_END}"
)

_AI_TARGETS = ("claude", "copilot", "cursor", "neutral")


def _expanded_sources_inline() -> str:
    return ", ".join(f"`{path}`" for path in _CONTEXT_REFERENCE_PATHS)


def _claude_knowledge_pointer() -> str:
    return f"@../{_PRIMARY_CONTEXT_PATH}\n"


def _copilot_inline() -> str:
    return (
        f"{_MARKER_START}\n"
        "Use the repository context generated by 2repo before proposing changes.\n"
        f"Primary context: `{_PRIMARY_CONTEXT_PATH}`\n"
        f"Expanded sources: {_expanded_sources_inline()}\n"
        f"{_MARKER_END}"
    )


def _cursor_rule() -> str:
    lines = [
        "---",
        "description: 2repo repository context",
        'globs: ["**/*"]',
        "alwaysApply: true",
        "---",
        "",
        "# Intentional: repository context must be applied globally for consistent sessions.",
        f"Use `{_PRIMARY_CONTEXT_PATH}` as the primary repository context.",
        "For detailed references consult:",
    ]
    lines.extend(f"- `{path}`" for path in _CONTEXT_REFERENCE_PATHS)
    lines.append("")
    return "\n".join(lines)


def _write_if_changed(path: Path, *, content: str) -> bool:
    if path.exists():
        if path.read_text(encoding="utf-8") == content:
            return False
        path.write_text(content, encoding="utf-8")
        return True
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return True


def _replace_or_append(path: Path, *, block: str) -> bool:
    """Replace the managed marker block in a file, or append/create it if missing."""
    if path.exists():
        content = path.read_text(encoding="utf-8")
        if _MARKER_START in content:
            updated = _MARKER_PATTERN.sub(block, content)
            return _write_if_changed(path, content=updated)
        updated = content.rstrip() + "\n\n" + block + "\n"
        return _write_if_changed(path, content=updated)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(block + "\n", encoding="utf-8")
    return True


def _inject_claude(repo: Path) -> list[str]:
    outputs: list[str] = []
    knowledge = repo / ".claude" / "KNOWLEDGE.md"
    if _write_if_changed(knowledge, content=_claude_knowledge_pointer()):
        outputs.append(str(knowledge))

    claude_md = repo / "CLAUDE.md"
    if _replace_or_append(claude_md, block=_CLAUDE_INLINE):
        outputs.append(str(claude_md))
    return outputs


def _inject_copilot(repo: Path) -> list[str]:
    copilot = repo / ".github" / "copilot-instructions.md"
    return [str(copilot)] if _replace_or_append(copilot, block=_copilot_inline()) else []


def _inject_cursor(repo: Path) -> list[str]:
    cursor_rule = repo / ".cursor" / "rules" / "2repo.mdc"
    return [str(cursor_rule)] if _write_if_changed(cursor_rule, content=_cursor_rule()) else []


def _inject_neutral(_repo: Path) -> list[str]:
    return []


_TARGET_WRITERS: dict[str, Callable[[Path], list[str]]] = {
    "claude": _inject_claude,
    "copilot": _inject_copilot,
    "cursor": _inject_cursor,
    "neutral": _inject_neutral,
}


def inject_for_target(repo_path: str, *, ai_target: str) -> list[str]:
    """Write integration files for one AI target and return created/updated paths."""
    repo = Path(repo_path)
    context = repo / "graphify-out" / "REPO_CONTEXT.md"
    if not context.exists():
        raise FileNotFoundError(f"required context artifact missing: {context}")
    if ai_target not in _AI_TARGETS:
        raise ValueError(f"invalid ai target '{ai_target}' (expected one of: {', '.join(_AI_TARGETS)})")

    return _TARGET_WRITERS[ai_target](repo)


def write_repo_context(
    repo_path: str,
    *,
    provider: str,
    model: str,
    index_revision: str,
    index_chunks: int,
    memory_count: int,
) -> Path:
    """Build graphify-out/REPO_CONTEXT.md summarizing canonical 2repo artifacts."""
    repo = Path(repo_path)
    out = repo / "graphify-out" / "REPO_CONTEXT.md"
    out.parent.mkdir(parents=True, exist_ok=True)

    lines: list[str] = []
    lines.append("# Repo Context")
    lines.append("")
    lines.append("_Canonical 2repo context source for AI editors._")
    lines.append("")
    lines.append("## Core Artifacts")
    for artifact_path, description in _CONTEXT_ARTIFACTS:
        lines.append(f"- `{artifact_path}` — {description}")
    wiki_dir = repo / "graphify-out" / "wiki"
    if wiki_dir.is_dir() and any(wiki_dir.glob("*.md")):
        lines.append(
            "- `graphify-out/wiki/` — living wiki: per-file documentation pages "
            "plus `OVERVIEW.md` (generated — do not edit by hand; regenerate with `2repo wiki <repo-path>`)"
        )
    lines.append("")
    lines.append("## Index Metadata")
    lines.append(f"- Provider: `{provider}`")
    lines.append(f"- Model: `{model}`")
    lines.append(f"- Index revision: `{index_revision}`")
    lines.append(f"- Indexed chunks: `{index_chunks}`")
    lines.append(f"- Memory entries: `{memory_count}`")
    lines.append("")
    lines.append("## Query")
    lines.append("- Semantic query: `2repo query <repo-path> \"your question\" --top-k 5`")
    lines.append("- Add durable memory: `2repo remember <repo-path> \"fact/decision/runbook\" --kind fact`")
    lines.append("")

    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return out
